- type: replace
  path: /product-properties/.properties.cloud_provider?
  value:
    value: AWS

- type: replace
  path: /product-properties/.properties.cloud_provider.aws.iam_instance_profile_master?
  value:
    value: ${iam_instance_profile_master}

- type: replace
  path: /product-properties/.properties.cloud_provider.aws.iam_instance_profile_worker?
  value:
    value: ${iam_instance_profile_worker}

- type: replace
  path: /resource-config/pivotal-container-service?/additional_vm_extensions?
  value: [${pks_api_lb_security_group}]

  